### ISSUE TITLE
Error at start using AUR on Manjaro

### ISSUE THREAD

**Issue by NicBOMB** [JoseExposito/touche#30]
### Describe the bug
Starting touche from plasma apps menu appeared to do nothing.
Starting touche from konsole got the following:
```(com.github.joseexposito.touche:2669): Gjs-CRITICAL **: 16:38:15.200: JS ERROR: Error: Module build failed (from ../touche-1.0.6/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-class-properties'
Require stack:
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/files/plugins.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/files/index.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/index.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/babel-loader/lib/index.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/loader-runner/lib/loadLoader.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/loader-runner/lib/LoaderRunner.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/webpack/lib/NormalModule.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/webpack/lib/NormalModuleFactory.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/webpack/lib/Compiler.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/webpack/lib/webpack.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/webpack/lib/index.js
- /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/bundle/scripts/build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at resolve (node:internal/modules/cjs/helpers:99:19)
    at resolveStandardizedName (/var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/files/plugins.js:100:7)
    at resolvePlugin (/var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/files/plugins.js:44:10)
    at loadPlugin (/var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at createDescriptor (/var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/var/tmp/pamac-build-nicbomb/touche/src/touche-1.0.6/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
@webpack:///../touche-1.0.6/src/index.js?:1:7
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:13:1
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:14:12
@/usr/bin/touche:11:1
```
This appears to be related to #4 @yochananmarqos

**Comment by yochananmarqos** [comment]
Whops. I thought [this](https://aur.archlinux.org/cgit/aur.git/commit/?h=touche&id=eeeffbc439e847c6430ca62d0245a971f30cd9a1) would be a good idea. Apparently not. 

I reverted the commit, it's fixed with 1.0.6-3.

**Comment by NicBOMB** [comment]
> Whoops. I thought [this](https://aur.archlinux.org/cgit/aur.git/commit/?h=touche&id=eeeffbc439e847c6430ca62d0245a971f30cd9a1) would be a good idea. Apparently not. @JoseExposito Any idea why that didn't work out?
> 
> I reverted the commit, it's fixed with 1.0.6-3.

Just built and is running. Thanks!

**Comment by JoseExposito** [comment]
I think that this bit is correct:

```bash
	if [ "$XDG_CURRENT_DESKTOP" = "Pantheon" ]; then
		arch-meson "$pkgname-$pkgver" build -Dtarget-de=elementary
	else
		arch-meson "$pkgname-$pkgver" build -Dtarget-de=gnome
	fi
```

However, it is still required to install the npm modules in `$pkgname-$pkgver` or webpack won't be able to find them. Thanks for fixing it!

**Comment by yochananmarqos** [comment]
Yeah, I realized moving the build folder is what did it. It's [implemented properly](https://aur.archlinux.org/cgit/aur.git/commit/?h=touche&id=c3cba99c7ec5a84398c10fd0f1b9b5e119a368f3) now.

**Comment by JoseExposito** [comment]
Cool, thanks a lot :smile: Not on Arch at the moment, but, is it missing the `meson compile -C build` step? The [wiki](https://wiki.archlinux.org/title/Meson_package_guidelines) recommends it, but maybe is not required.

**Comment by yochananmarqos** [comment]
Oops, copy / paste error. Time for more coffee. 🤣
